### ISSUE TITLE
Remove list of lists returned by get_center_input_file

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/synapsegenie#32]
https://github.com/Sage-Bionetworks/synapsegenie/blob/cf7b6b31cf35b1ef16d515d3fcae3b41e7c2cddf/synapsegenie/input_to_database.py#L60

**Comment by adamjtaylor** [comment]
This feature was initially in place for paired files such as R1 and R2 FASTQ files. As this is a limited use case this should return just a list of entities. Where paired file validation is required the pairs can be found from the list of entities as part of a validation function.
