### ISSUE TITLE
Update synapse_login

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/synapsegenie#33]
* Support PAT env variable
* Support service catalog scheduled jobs env variable
https://github.com/Sage-Bionetworks/synapsegenie/blob/5034bd6f51abf4b3eeaebff117a2b1dd130f7476/synapsegenie/__main__.py#L19

**Comment by adamjtaylor** [comment]
Currently a pat in ~/.synapseConfig does work and is OK until we move to scheduled jobs
